// Generated by CoffeeScript 1.5.0-pre
(function() {
  var CoffeeScript, merge, repl, replDefaults, vm;

  vm = require('vm');

  repl = require('repl');

  CoffeeScript = require('./coffee-script');

  merge = require('./helpers').merge;

  replDefaults = {
    prompt: "coffee> ",
    "eval": function(code, context, file, cb) {
      try {
        if (/^\(\s+\)$/.test(code)) {
          code = '';
        }
        code = CoffeeScript.compile(code, {
          filename: file,
          bare: true
        });
        return cb(null, vm.runInContext(code, context, file));
      } catch (err) {
        return cb(err);
      }
    }
  };

  module.exports = {
    start: function(opts) {
      if (opts == null) {
        opts = {};
      }
      return repl.start(merge(replDefaults, opts));
    }
  };

}).call(this);
